name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instal Dependencies
        run: bun install

      - name: Run tests
        run: bun test --reporter=dots --reporter=junit --reporter-outfile=junit.xml
        env:
          FORCE_COLOR: 1
